name: Sync Repository
on:
  workflow_dispatch:

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          source-directory: .
          target-directory: 'api'
          destination-github-username: 'bryanz994'
          destination-repository-name: 'neo4j_enigma'
          target-branch: main
